require 'rspec/core/rake_task'

task :default => :run

desc "Run TIC Tac Toe"
task :run do 
  ruby "-w lib/TicTacToe.rb"
end

desc "Run tests on TicTacToe"
RSpec::Core::RakeTask.new(:spec) do |task|
  task.rspec_opts = "-c -w"
  task.verbose = false
end