require 'rspec/core/rake_task'

task :default => :run

desc "Run Connect Four"
task :run do 
  ruby "-w lib/connect_four.rb"
end

desc "Run tests on Connect Four"
RSpec::Core::RakeTask.new(:spec) do |task|
  task.rspec_opts = "-c -w"
  task.verbose = false
end