require 'rspec/core/rake_task'

task :default => :run

desc "Run Enumerable Methods"
task :run do 
  ruby "-w lib/enumerable_methods.rb"
end

desc "Run tests on Enumerable Methods"
RSpec::Core::RakeTask.new(:spec) do |task|
  task.rspec_opts = "-c -w"
  task.verbose = false
end