require 'rspec/core/rake_task'

task :default => :run

desc "Run caesar's cipher"
task :run do 
  ruby "-w lib/CaesarCipher.rb"
end

desc "Run tests on caesar's cipher"
RSpec::Core::RakeTask.new(:spec) do |task|
  task.rspec_opts = "-c -w"
  task.verbose = false
end